# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premise',
            old_name='name_text',
            new_name='name',
        ),
    ]
